### ISSUE TITLE
Plugin not working in 1.9.2

### ISSUE THREAD

**Issue by waltersajtos** [kevinhayen/grandma3_fixture_to_presets#1]
When pressing the plugin and selecting a fixture I get the following screen:

![image](https://github.com/kevinhayen/grandma3_fixture_to_presets/assets/32552097/8f3e9ed8-8b72-4f3e-b81f-af7d4e08b71b)

I am on windows onPc 1.9.2.2

**Comment by JJFlies** [comment]
I got the same issue have not been able to find a solution. Command line says Indexing error.
