### ISSUE TITLE
Cannot merge presets

### ISSUE THREAD

**Issue by mokabyls** [kevinhayen/grandma3_fixture_to_presets#2]
First of all a big thank you for this very useful plugin!

everything works fine but, when I have presets (empty or not) already created, the plugin prevents me from "merge" in them even if I check the "merge" box. Impossible to tell him, I want to merge on preset X.

Example :

1 - In the "Gobo" pool for example, I create 10 empty presets to which I assign an appearance (from 3.1 Thru 3.10).
2 - In a sequence, I assign each preset to a cue.
3 - Later, I add fixtures to my patch.
3 - When I launch the plugin, it prevents me, even if I check "merge", from saving on the 3.X preset.

I think the problem most definitely comes from the "fixture_to_presets_find_first_empty_preset" method. Maybe it would be interesting to add in the plugin:

- If merge is checked, allow to select any preset via the "<" / ">" button or to enter the desired number directly.

WDYT?

**Comment by kevinhayen** [comment]
Hi,

I do understand it's a bit confusing to see the arrows with the number, while "Merge" is checked. 
It's not clearly visible that the arrows with the number are overruled when "Merge" is checked.

Currently it has 2 workflows:
- "Merge" not checked: the number and arrows are to navigate an empty preset, and the preset is stored by clicking a shown value
- "Merge" checked: By pressing one of the shown values, an input box pops up, asking where you want to merge that value

I just tested this on a new showfile having one fixture patched, and it works for me when creating an empty preset having an appearance, who I update when "Merge" is checked.

But indeed, I can change that workflow, so the number and arrows are also used when "Merge" is checked.

On top of this, your question raises an extra feature, where I want the plugin to ask if it wants to override the currently linked appearance with the new appearance

**Comment by kevinhayen** [comment]
Hi,

I updated the code so now the arrows are also used when "Merge" is checked.
When unchecking "Merge", the navigator will verify if the current visible number is related to an empty preset. If not, the number in the navigator will be changed to the next empty preset, and show a popup to inform the user about this change.

**Comment by mokabyls** [comment]
Thank you @kevinhayen !
