### ISSUE TITLE
Indexing Error

### ISSUE THREAD

**Issue by JJFlies** [kevinhayen/grandma3_fixture_to_presets#3]
When opening Plugin on MA3 all i get is a blank prompt not detecting any fixtures in the patch. Command Line says " error attempt to index a nil value"

**Comment by kevinhayen** [comment]
@JJFlies does at least one fixture have a fixtureID in your patch? Is it possible to paste a screenshot of your patched fixtures? or send me your showfile to kevinhayen@gmail.com
I will check when I'm at home on the latest version

**Comment by JJFlies** [comment]
@kevinhayen I found the issue only occurred when I had geometry objects from MVR in my patch. Once i delete all of my MVR data the plug-in seems to work fine.

**Comment by kevinhayen** [comment]
@JJFlies is it possible to create that patch and send this to my email address? Maybe I can implement some logics to deny those MVR data, and not giving any error regarding "nil value"

**Comment by JJFlies** [comment]
yes i will send MVR file to your email

**Comment by o0oRMXo0o** [comment]
Hello together,

I have the same problem.
Imported an mvr und with all the geometry the plugin didn’t find any fixture.
When I deleted all the geometry then the Plugin find all my fixtures.

it would be amazing when the plugin works with all the geometric parts

greets from Germany

**Comment by kevinhayen** [comment]
@o0oRMXo0o thank you for this info, I will try to fix this

**Comment by kevinhayen** [comment]
@JJFlies @o0oRMXo0o is it possible to email me one of your mvr files which caused the issue? I try to recreate the issue here, but I end up with other behaviors. My email is kevinhayen@gmail.com

**Comment by kevinhayen** [comment]
This is fixed, just updated the xml file
